### ISSUE TITLE
Too small throat  in flow sensor

### ISSUE THREAD

**Issue by Blimpyway** [cpvyb/OpenRespirator#1]
Hi, 

Looking at slide 3 on the  [flow meter description file](https://github.com/cpvyb/OpenRespirator/blob/master/Doc/Gas%20port%20with%20flow%20sensor-2.pptx) I noticed the smallest orifice in the airway is 2.5mm diameter (the one indicated as "2.5mm orifice with chamfered edge..") . 

This is way too small at an inhalation/exhalation rate of 0.5l/sec (and it can be higher at high BPM) it creates a 62cm pressure drop (6250 Pa). 
Beware patient's pressure ranges between 0cm-15cm peep  and up to 40cm pip (peak inhalation pressure)  levels. 

It not only alters pressure readings but also impedes respiration itself.  Try to breathe through a 2.5mm pipe. 

In order to not alter breathing measurements by sensors themselves, they should create significantly less than ~1cm (100 Pa) pressure difference with their presence.

**Comment by cpvyb** [comment]
Thanks for your comment. Final implementation has 6 mm orifice.

**Comment by cpvyb** [comment]
.
